### ISSUE TITLE
add option to delete pet

### ISSUE THREAD

**Issue by WitchDevelops** [WitchDevelops/cardboard-fort#62]
this will be added in two places:
1. in the pet card, top right corner
2. in the pet page

Both will function like this:
three vertical dots menu opens a dropdow with "delete pet", clicking this opens a modal that confirms the action.

1. pet card
![image](https://github.com/user-attachments/assets/86a79d6f-d821-4b90-b2c7-cc1e2f887020)

2. pet page

![Image](https://github.com/user-attachments/assets/29d330b1-35ba-482d-a050-b5e4335dc4cc)

![Image](https://github.com/user-attachments/assets/1347ff88-dfec-4773-b6d1-5f1b591606cf)

**Comment by WitchDevelops** [comment]
Added to the pet card:
![image](https://github.com/user-attachments/assets/2cb2b35c-0f82-456b-a3d2-faf16a8f2962)
![image](https://github.com/user-attachments/assets/860166b7-64da-49c7-9d91-82d3db052fca)
![image](https://github.com/user-attachments/assets/ab50c4c5-de06-419c-8244-26d864d92570)

**Comment by WitchDevelops** [comment]
**TODO:**

- [ ] add a toast that shows confirmation message that the pet was successfully removed
- [ ] make the delete work from the level of the pet page
- [ ] navigate to the view with all pets after removing one from the view of pet page
